---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_alpine_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform == 'alpine'"
- platform: "debian"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_debian_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'debian'"
- platform: "centos6"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_centos6_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 6"
- platform: "centos7"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_centos7_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 7"
- platform: "centos8"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_centos8_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
  -  "entity.system.platform_family == 'rhel'"
  -  "parseInt(entity.system.platform_version.split('.')[0]) == 8"
    
